### ISSUE TITLE
Possible Nvidia compiler bugs

### ISSUE THREAD

**Issue by raphlinus** [linebender/piet-gpu#10]
I'm running into a number of cases where either the Nvidia shader compiler crashes (which seems pretty obviously bad) or I'm getting unexplained bad results on Nvidia with no comparable problem on Intel. This issue is to investigate whether it is actually shader compiler bugs or something I'm doing wrong, and whether there are workarounds. There are 3 separate subcases but they may well be related.

These are all reported against a laptop GTX 1060, in a Gigabyte Aero 14, running Windows 10 build 19041.264, and Nvidia driver 445.87.0.0.

## Case 1: shader compiler crash

This can be repro'ed  from scratch by the following steps:

```sh
git clone https://github.com/linebender/piet-gpu
cd piet-gpu
git checkout nv_crash_1
cd piet-gpu
cargo run
```

On two machines, this results in a STATUS_ACCESS_VIOLATION deep inside the shader compiler, in the VkCreateComputePipelines call (I can provide stack traces etc if needed).

There is a workaround, which can be applied by checking out `nv_crash1~` (ie the head commit in that branch is a revert of the workaround). This is a very small change and appears to be completely semantics-invariant. With the workaround, the example runs fine (producing a beautiful abstract artwork in image.png).

## Case 2: ERROR_DEVICE_LOST

```sh
git clone https://github.com/linebender/piet-gpu
cd piet-gpu
git checkout nv_crash_2
cd piet-gpu
cargo run --bin cli
```

Again there is a workaround, but it's extremely fragile; almost any perturbation will provoke failure. And again the workaround looks to be completely semantics preserving (there's no chance that `bin_ix` can have this value; I came up with this while trying to figure out which bin was responsible).

This is the one I have the least confidence is a driver bug, but I've done a considerable amount of work trying to track down possible errors on my side, and of course it works fine on Intel.

## Case 3: shared memory corruption

```sh
git clone https://github.com/linebender/piet-gpu
cd piet-gpu
git checkout nv_bug_3
cd piet-gpu
cargo run --bin cli
```

In this case, the element.comp kernel runs but produces incorrect output. Again the workaround looks to be entirely semantics preserving. Inspecting the output carefully, it seems the `sh_state` array is being corrupted, it looks like elements being written to a wrong offset (the `mat` field can never be anything other than [1, 0, 0, 1] in this example, but looking at intermediate values it sometimes takes values from other fields such as linewidth).

Again, it's possible I'm doing something wrong (some undefined behavior somewhere) but I've looked pretty hard, and it runs fine on Intel.

Obviously, any help in further tracking these down would be appreciated.

**Comment by raphlinus** [comment]
Also note that the shaders can be recompiled with `(cd shader && ninja)`.

**Comment by raphlinus** [comment]
I also tried with the developer branch driver (443.15.0.0) and got very similar results, except that in case 2 instead of ERROR_DEVICE_LOST I got NOT_READY when reading vkGetQueryPoolResults. Basically very similar failure mode, in both cases it seems like the kernel is not completing.

**Comment by raphlinus** [comment]
I've done some more digging into crash 2, instrumenting the kernel to output its activity for bin 0, which has only 3 segments, therefore is fairly easy to analyze. The updated code is in the nv_crash_2 branch, and I also put the [log output](https://gist.github.com/raphlinus/feb03d8c6b443f79c95f9352b4bd92cc) in a gist. This shows the trace of `log_value` calls for each of the 256 threads in the workgroup.

The trace of "shared minimum element" is supposed to be the same for all threads, as the read of it is protected by a (dynamically uniform) `barrier()` call. The correct sequence is shown in the first 16 (= N_WG) threads: 1, 74e, 828). Thread 10 (hex) is seeing 408, which is the incorrect value. On other runs, I've seen 3f800000, so this seems to be some kind of uninitialized value.

**Comment by rhzk** [comment]
I think case 3 is caused by mismatched structure sizes in rust and shaders

From the vulkan specs:
* An array has a base alignment equal to the base alignment of its element type.
* A structure has a base alignment equal to the largest base alignment of any of its members.

https://www.khronos.org/registry/vulkan/specs/1.0-wsi_extensions/html/vkspec.html#interfaces-resources-layout

In the code we have
```rust
struct State {
   mat: [f32; 4],
   translate: [f32; 2],
   bbox: [f32; 4],
   linewidth: f32,
   flags: u32,
   path_count: u32,
   pathseg_count: u32,
}
```
This has a size of 56 bytes, and its higest member is a vec4, that has a size of 16 bytes
Meaning that the array has a 16 byte alignment on the shaders.

As an example modifying the state struct to have a size of 64 bytes, a multiple of 16 (and changing elements.comp to use array of struct)  draws the tiger image correctly on my nvidia gtx 1060

```rust
struct State {
   mat: [f32; 4],
   translate: [f32; 2],
   bbox: [f32; 4],
   linewidth: f32,
   flags: u32,
   path_count: u32,
   pathseg_count: u32,
   padd_to_64: [f32;2],
}
```

**Comment by raphlinus** [comment]
I'm going to close this, as the bugs have been fixed in the driver. It was a struct size/alignment issue, but there was at least one problem that wasn't my code. Keep in mind that the shader code that reads the Rust-serialized struct is not just doing a read in GLSL of the struct, but reading the 32 bit words from the buffer. Thus, the struct in the buffer *need not* have the same alignment requirements as a GLSL struct, as in a structured buffer.
