### ISSUE TITLE
Duplicate reparsing in SVG Rendering native example

### ISSUE THREAD

**Issue by simbleau** [linebender/piet-gpu#161]
render_svg() in the example is loading and reparsing the file every frame, which was definitely not intended... I'll make a PR tomorrow or soon when I have time to fix that.

**Comment by raphlinus** [comment]
Heh yes. One reason I haven't done anything about this is that we intend to put in an API for scene fragments. With that API, you'd load, parse, and create a fragment once, then render that fragment (possibly with different scale, clip, blend, etc) as many times as you like.

But that won't land for a bit so it makes sense to have something in place to get meaningful measurements.
