### ISSUE TITLE
Shader compilation plan

### ISSUE THREAD

**Issue by raphlinus** [linebender/piet-gpu#177]
It's super annoying and error-prone to compile shaders and check the generated code into the repo. Yet there are advantages to having the generated code checked in, particularly not requiring extra tools to build and run, and also pinning those tools to a specific version, for repeatability.

The proposed solution is for the source of truth to be GitHub Actions that compile the shaders. Here is a somewhat more detailed plan.

All commits (and PRs) go to a newly created `dev` branch. This branch has no shader/gen directories. Thus, the PR contains changes to the shader source but not any compiled artifacts. The `main` branch tracks `dev` closely but has the gen subdirectories. A GitHub action runs on pushes to the dev branch and creates a commit to `main` updating the gen subdirectories.

This action runs on Windows, which gives us access to both the official DXIL signing DLL and also the Windows port of [Metal tools](https://developer.apple.com/documentation/metal/shader_libraries/building_a_library_with_metal_s_command-line_tools) (subject to figuring out how to download the latter). In future, we are likely to add to the sophistication of shader compilation in various ways, including getting metadata programmatically (binding renumbering on MSL/HLSL, workgroup size, etc), spinning more permutations. Instead of shell/ninja, we may move to a Rust tool, possibly using [hassle-rs](https://docs.rs/hassle-rs/latest/hassle_rs/) and related tools.

**Comment by DJMcNab** [comment]
Have we checked the historical size of the compiled shaders - that is, is it worth doing a clean break of `dev`'s history?
